name: bridge-ml
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pytorch>=1.9.0
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - tensorflow>=2.6.0
  - numpy>=1.19.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - matplotlib>=3.4.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pytest>=6.0.0
  - sphinx>=4.0.0
  - pip:
    - torch-geometric>=2.0.0
    - networkx>=2.6.0
    - rdflib>=6.0.0
    - owlready2>=0.36